### PR TITLE
Add Mailhog extension

### LINKED ISSUE #3: Consider including Chassis/Mailhog
Mailhog is very handy for logging outgoing emails during development, particularly because email sent from unauthenticated servers will rarely actually arrive at their destination, and particularly for avoiding unintentionally sending emails to actual users.

The Chassis/Mailhog extension installs Mailhog and configures sendmail on the server to send all emails through it.

I think this is a good candidate for installing by default.

### PR DESCRIPTION
**Pull request by roborourke**
Also brings us towards feature parity with `local-server`

Fixes #3

### CODE REVIEW

**Comment by rmccue** [comment]
I am 👎 on this. The extension should be fairly minimal and only include what we need to run stuff, not every developer tool.

**Comment by mattheu** [comment]
One big advantage of having Mailhog by default is that it reduces the risk that people will send emails to real users from a local site by accident. 

Of course there are probably better ways to solve this, but having mail disabled locally, with an extension like MailHog to expose it, seems like it could be a valuable addition.

**Comment by rmccue** [comment]
That's true, and it does sit in this weird spot where it's half a dev tool and half a piece of functionality. I'm just wary of adding everything in; it can also be a bit confusing to call `wp_mail` and have it not deliver the email.

I wonder if maybe we could rethink this: what if we built MailHog-like functionality directly into the Altis dev tools?

**Comment by johnbillion** [comment]
Alternatively there's the Email Log plugin for WordPress which I've used in the past, but there's definitely value in catching outgoing emails during development regardless of where they're sent from.

As per my summary on #3, you're lucky if an email sent from a local dev server actually arrives at its destination.

**Comment by roborourke** [comment]
If we want to include services like this via the dev-tools module then this looks good https://mailocal.jfoucher.com/

I would question why it was ok to use mailhog for `local-server` but not `local-chassis`. Email is a fundamental part of the application so should be handled out of the box in my opinion. Unless you're testing SES itself or an alternative email delivery service shouldn't be affected by having a default sendmail handler.

**Comment by roborourke** [comment]
> That's true, and it does sit in this weird spot where it's half a dev tool and half a piece of functionality.

On this note I'd argue that the local dev environment is a dev tool itself.

**Comment by rmccue** [comment]
You're right; let's go ahead and ship this then, and investigate a broader solution that's more integrated with our dev tools suite.

**Review by rmccue — APPROVED** [review]

**Pull request merged**
